name: wireapp
description: e-commerce technical test

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  hooks_riverpod: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true